### ISSUE TITLE
Crashing on Hyprland

### ISSUE THREAD

**Issue by LDAP** [pierrechevalier83/workstyle#46]
workstyle is currently crashing on hyprland. The console shows:

```
[2023-03-19T15:40:07Z ERROR workstyle] Couldn't identify window: Window { name: Some("Freunde - Discord"), app_id: None, window_properties_class: Some("discord") }
[2023-03-19T15:40:07Z ERROR workstyle] panicked at 'called `Result::unwrap()` on an `Err` value: ParseIntError { kind: PosOverflow }', src/window_manager.rs:244:25
```

**Comment by pierrechevalier83** [comment]
> workstyle is currently crashing on hyprland. The console shows:
> 
> ```
> [2023-03-19T15:40:07Z ERROR workstyle] Couldn't identify window: Window { name: Some("Freunde - Discord"), app_id: None, window_properties_class: Some("discord") }
> [2023-03-19T15:40:07Z ERROR workstyle] panicked at 'called `Result::unwrap()` on an `Err` value: ParseIntError { kind: PosOverflow }', src/window_manager.rs:244:25
> ```

Thanks for the report. I just noticed this as well when launching steam. I've pushed a quick fix. Can you try the latest commit on main and let me know whether it fixes it?

**Comment by LDAP** [comment]
Yes. I could not get it to crash with the latest commit.
