### ISSUE TITLE
Thread 'main' panicked

### ISSUE THREAD

**Issue by peter-si** [pierrechevalier83/workstyle#7]
Hi, i've installed workstyle through AUR, but I'm getting this error, when trying to  run it
```bash
❯ RUST_BACKTRACE=full workstyle
thread 'main' panicked at 'attempted to leave type `linked_hash_map::Node<std::string::String, value::Value>` uninitialized, which is invalid', /build/rust/src/rustc-1.48.0-src/library/core/src/mem/mod.rs:658:9
stack backtrace:
   0:     0x5592bd11b780 - <unknown>
   1:     0x5592bd13f70c - <unknown>
   2:     0x5592bd117e25 - <unknown>
   3:     0x5592bd11d99d - <unknown>
   4:     0x5592bd11d648 - <unknown>
   5:     0x5592bd11e081 - <unknown>
   6:     0x5592bd11dc29 - <unknown>
   7:     0x5592bd11bbec - <unknown>
   8:     0x5592bd11dbe9 - <unknown>
   9:     0x5592bd13dfb1 - <unknown>
  10:     0x5592bd13defd - <unknown>
  11:     0x5592bd0f688a - <unknown>
  12:     0x5592bd0fdc5c - <unknown>
  13:     0x5592bd0e9593 - <unknown>
  14:     0x5592bd0fc256 - <unknown>
  15:     0x5592bcffbcbd - <unknown>
  16:     0x5592bcffa436 - <unknown>
  17:     0x5592bcff6dc3 - <unknown>
  18:     0x5592bcff6e09 - <unknown>
  19:     0x5592bd11e4a7 - <unknown>
  20:     0x5592bcffaa92 - <unknown>
  21:     0x7f48c8c74152 - __libc_start_main
  22:     0x5592bcff509e - <unknown>
  23:                0x0 - <unknown>
```
I have:
Rust  `Version         : 1:1.48.0-1`
workstyle-git `Version         : 0.2.1.r29.g43b0b5b-1
kernel `Version         : 5.9.14.arch1-1`

Any idea, what the  problem can be? Thank you.

P.S.: this package looks very good. I was using [i3scripts](https://github.com/justbuchanan/i3scripts/blob/master/autoname_workspaces.py) for this renaming, but it broke and having to copy/paste script is not very user friendly. I especially like configurable icons :wink:

**Comment by zsolt-donca** [comment]
I have the same issue as stated here: same packager (AUR) on the same version, producing the same stacktrace.

**Comment by thecatwasnot** [comment]
I'm getting the same error, looks like I have a newer version of rust.  Error occurs specifically when I move the mouse to another window on the same monitor or to the other monitor.  I have 2 monitors.  I'm using sway/waybar.
```
RUST_BACKTRACE=full workstyle
thread 'main' panicked at 'attempted to leave type `linked_hash_map::Node<std::string::String, value::Value>` uninitialized, which is invalid', /build/rust/src/rustc-1.49.0-src/library/core/src/mem/mod.rs:659:9
stack backtrace:
   0:     0x55bfe57563c0 - <unknown>
   1:     0x55bfe577b06c - <unknown>
   2:     0x55bfe5752ae5 - <unknown>
   3:     0x55bfe5758795 - <unknown>
   4:     0x55bfe5758438 - <unknown>
   5:     0x55bfe5758f31 - <unknown>
   6:     0x55bfe5758a47 - <unknown>
   7:     0x55bfe575687c - <unknown>
   8:     0x55bfe57589d9 - <unknown>
   9:     0x55bfe57799a1 - <unknown>
  10:     0x55bfe57798ed - <unknown>
  11:     0x55bfe57313aa - <unknown>
  12:     0x55bfe573778c - <unknown>
  13:     0x55bfe5724133 - <unknown>
  14:     0x55bfe5736d76 - <unknown>
  15:     0x55bfe5635eed - <unknown>
  16:     0x55bfe5634896 - <unknown>
  17:     0x55bfe5637833 - <unknown>
  18:     0x55bfe5637849 - <unknown>
  19:     0x55bfe5759357 - <unknown>
  20:     0x55bfe5634ee2 - <unknown>
  21:     0x7f84c80d8152 - __libc_start_main
  22:     0x55bfe562f09e - <unknown>
  23:                0x0 - <unknown>
```
`workstyle-git 0.2.1.r29.g43b0b5b-1` from the AUR

**Comment by m47730** [comment]
i fix it simply update _toml_ library version to **_0.5.8_**

**Comment by pierrechevalier83** [comment]
Addressed thanks to @FlorianFranzen's fix :smile: Sorry for the long inactivity. My notifications weren't set correctly and I lost track of everything that happened in this repo for the past many months.
